all:
	c++ -I /usr/local/include -L /usr/local/lib -o ./out/AssignVectorTest ./src/AssignVectorTest.cpp
	c++ -I /usr/local/include -L /usr/local/lib -o ./out/SingletonTest ./src/SingletonTest.cpp
clean:
	rm -rf ./out/* 