all:
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/ScopedPtrTest ./src/ScopedPtrTest.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/ScopedArrTest ./src/ScopedArrTest.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/SharedPtrTest1 ./src/SharedPtrTest1.cpp
clean:
	rm -rf ./out/*
