all:
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/ScopedPtrTest ./src/ScopedPtrTest.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/ScopedArrTest ./src/ScopedArrTest.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/SharedPtrTest1 ./src/SharedPtrTest1.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/SharedPtrTest2 ./src/SharedPtrTest2.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/SharedPtrFactory ./src/SharedPtrFactory.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/SharedPtrTest3 ./src/SharedPtrTest3.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/SharedPtrTest3 ./src/SharedPtrTest3.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/SharedPimplTest ./src/SharedPimplTest.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/SharedPtrDelTest ./src/SharedPtrDelTest.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/WeakPtrTest ./src/WeakPtrTest.cpp
	c++ -I /usr/local/include/ -L /usr/local/lib/ -o ./out/ThisPtrTest ./src/ThisPtrTest.cpp
clean:
	rm -rf ./out/*
