all:
	# c++ -I /usr/local/include -L /usr/local/lib -lboost_date_time -lboost_system  -o ./out/DeadlineTest ./src/DeadlineTest.cpp
	# c++ -I /usr/local/include -L /usr/local/lib -lboost_date_time -lboost_system -o ./out/DeadlineAsyncTest ./src/DeadlineAsyncTest.cpp
	# c++ -I /usr/local/include -L /usr/local/lib -lboost_date_time -lboost_system -o ./out/BindTimerTest ./src/BindTimerTest.cpp
	# c++ -I /usr/local/include -L /usr/local/lib -lboost_system -o ./out/SyncServerTest ./src/SyncServerTest.cpp
	g++ -I /usr/local/include -L /usr/local/lib -lboost_system -std=c++11 -o ./out/ChatClient ./src/ChatClient.cpp
	g++ -I /usr/local/include -L /usr/local/lib -lboost_system -std=c++11 -o ./out/ChatServer ./src/ChatServer.cpp

